// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: feeling.sql

package db

import (
	"context"
)

const createFeeling = `-- name: CreateFeeling :one
INSERT INTO feeling (
    product_id,
    user_id,
    username,
    comment,
    recommend
) VALUES (
    $1, $2, $3, $4, $5
) 
RETURNING id, product_id, user_id, username, comment, recommend, created_at
`

type CreateFeelingParams struct {
	ProductID int64  `json:"product_id"`
	UserID    int64  `json:"user_id"`
	Username  string `json:"username"`
	Comment   string `json:"comment"`
	Recommend bool   `json:"recommend"`
}

func (q *Queries) CreateFeeling(ctx context.Context, arg CreateFeelingParams) (Feeling, error) {
	row := q.db.QueryRow(ctx, createFeeling,
		arg.ProductID,
		arg.UserID,
		arg.Username,
		arg.Comment,
		arg.Recommend,
	)
	var i Feeling
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.UserID,
		&i.Username,
		&i.Comment,
		&i.Recommend,
		&i.CreatedAt,
	)
	return i, err
}

const deleteFeeling = `-- name: DeleteFeeling :exec
DELETE FROM feeling WHERE id = $1
`

func (q *Queries) DeleteFeeling(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteFeeling, id)
	return err
}

const getFeeling = `-- name: GetFeeling :one
SELECT id, product_id, user_id, username, comment, recommend, created_at FROM feeling
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetFeeling(ctx context.Context, id int64) (Feeling, error) {
	row := q.db.QueryRow(ctx, getFeeling, id)
	var i Feeling
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.UserID,
		&i.Username,
		&i.Comment,
		&i.Recommend,
		&i.CreatedAt,
	)
	return i, err
}

const listFeelings = `-- name: ListFeelings :many
SELECT id, product_id, user_id, username, comment, recommend, created_at FROM feeling
ORDER BY id
LIMIT $1
OFFSET $2
`

type ListFeelingsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListFeelings(ctx context.Context, arg ListFeelingsParams) ([]Feeling, error) {
	rows, err := q.db.Query(ctx, listFeelings, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Feeling{}
	for rows.Next() {
		var i Feeling
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.UserID,
			&i.Username,
			&i.Comment,
			&i.Recommend,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFeelingsByProductId = `-- name: ListFeelingsByProductId :many
SELECT id, product_id, user_id, username, comment, recommend, created_at FROM feeling
WHERE product_id = $1
ORDER BY id
LIMIT $2
OFFSET $3
`

type ListFeelingsByProductIdParams struct {
	ProductID int64 `json:"product_id"`
	Limit     int32 `json:"limit"`
	Offset    int32 `json:"offset"`
}

func (q *Queries) ListFeelingsByProductId(ctx context.Context, arg ListFeelingsByProductIdParams) ([]Feeling, error) {
	rows, err := q.db.Query(ctx, listFeelingsByProductId, arg.ProductID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Feeling{}
	for rows.Next() {
		var i Feeling
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.UserID,
			&i.Username,
			&i.Comment,
			&i.Recommend,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFeelingsByUserId = `-- name: ListFeelingsByUserId :many
SELECT id, product_id, user_id, username, comment, recommend, created_at FROM feeling
WHERE user_id = $1
ORDER BY id
LIMIT $2
OFFSET $3
`

type ListFeelingsByUserIdParams struct {
	UserID int64 `json:"user_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListFeelingsByUserId(ctx context.Context, arg ListFeelingsByUserIdParams) ([]Feeling, error) {
	rows, err := q.db.Query(ctx, listFeelingsByUserId, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Feeling{}
	for rows.Next() {
		var i Feeling
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.UserID,
			&i.Username,
			&i.Comment,
			&i.Recommend,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFeeling = `-- name: UpdateFeeling :one
UPDATE feeling SET product_id = $2, user_id = $3, username = $4, comment = $5, recommend = $6
WHERE id = $1
RETURNING id, product_id, user_id, username, comment, recommend, created_at
`

type UpdateFeelingParams struct {
	ID        int64  `json:"id"`
	ProductID int64  `json:"product_id"`
	UserID    int64  `json:"user_id"`
	Username  string `json:"username"`
	Comment   string `json:"comment"`
	Recommend bool   `json:"recommend"`
}

func (q *Queries) UpdateFeeling(ctx context.Context, arg UpdateFeelingParams) (Feeling, error) {
	row := q.db.QueryRow(ctx, updateFeeling,
		arg.ID,
		arg.ProductID,
		arg.UserID,
		arg.Username,
		arg.Comment,
		arg.Recommend,
	)
	var i Feeling
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.UserID,
		&i.Username,
		&i.Comment,
		&i.Recommend,
		&i.CreatedAt,
	)
	return i, err
}
